export enum EditorActionTypes {
  INITIALIZE_STATE = '@classes/INITIALIZE_STATE',
  RESET_STATE = '@classes/RESET_STATE',
  SELECT_CLASS = '@classes/SELECT_CLASS',
  DELETE_ANNOTATION = '@classes/DELETE_ANNOTATION',
  ADD_ANNOTATION = '@classes/ADD_ANNOTATION',
  UPDATE_ANNOTATION = '@classes/UPDATE_ANNOTATION',
  MOVE_ANNOTATION = '@classes/MOVE_ANNOTATION',
  ADD_SHAPE = '@classes/ADD_SHAPE',
  DELETE_SHAPE = '@classes/DELETE_SHAPE',
  UPDATE_SHAPE = '@classes/UPDATE_SHAPE',
  ADD_ERASER_LINES = '@classes/ADD_ERASER_LINES',
  SET_COMMENTS = '@classes/SET_COMMENTS',
}
