import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { PATH_DASHBOARD } from 'src/routes/dashboard/paths';
import styles from '../styles/Home.module.css';
import OCR from './ocr';

const Home: NextPage = () => {
  const [img, setImg] = useState<File>();
  const [showOcr, setShowOCr] = useState(false);
  const { pathname, push } = useRouter();

  const handleSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();
    if (img) {
      setShowOCr(true);
    }
  };

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (!e.target.files || e.target.files.length !== 1) {
      return;
    }

    let image = e.target.files[0];
    setImg(image);
  };

  useEffect(() => {
    if (pathname === PATH_DASHBOARD.root) {
      // got to the projects page
      push(PATH_DASHBOARD.project.list);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname]);

  return null;

  return showOcr && img ? (
    <OCR img={img} />
  ) : (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>Image Annotation App</h3>
        <form onSubmit={handleSubmit}>
          <input
            type="file"
            id="anno-img-upload"
            name="Image"
            onChange={handleImageChange}
            accept="image/png, image/jpeg"
          />
          <input type="submit" value="Start Annotating" />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by DataPure
        </a>
      </footer>
    </div>
  );
};

export default Home;
