export enum EditorActionTypes {
  SELECT_LAYER = '@layers/SELECT_LAYER',
  DELETE_INSTANCE = '@layers/DELETE_INSTANCE',
  ADD_INSTANCE = '@layers/ADD_INSTANCE',
  UPDATE_INSTANCE = '@layers/UPDATE_INSTANCE',
  ADD_SHAPE = '@layers/ADD_SHAPE',
  DELETE_SHAPE = '@layers/DELETE_SHAPE',
  UPDATE_SHAPE = '@layers/UPDATE_SHAPE',
  ADD_ERASER_LINES = '@layers/ADD_ERASER_LINES',
  SET_COMMENTS = '@layers/SET_COMMENTS',
}
